---
- hosts: linux
  become: yes
  tasks:
  - name: install apache on ubuntu
    apt:
      name: apache2
      state: latest
      update_cache: true
    when: ansible_os_family == "Debian"
  - name: install apache on centos
    yum:
      name: httpd
      state: latest
    when: ansible_os_family == "RedHat"
  - name: start apache service on ubuntu
    service:
      name: apache2
      state: started
      enabled: true
    when: ansible_os_family == "Debian"
  - name: start apache service on centos
    service:
      name: httpd
      state: started
      enabled: true
    when: ansible_os_family == "RedHat"
  - name: Copy Index.html files to nodes
    copy:
      src: /etc/ansible/playbooks/index.html.j2
      dest: /var/www/html/index.html
